const VARIABLE_DEFINITIONS = [
  { name: 'CUST_BROKER',             type: 'toggle',  values: ['1', '10'], description: 'Broker flag (1 = Forsia og andre, 10 = DFHF)' },
  { name: 'CUST_NAME',               type: 'text',                         description: 'Kundenavn' },
  { name: 'POL_LINE_EXCESS',         type: 'number',                       description: 'Selvrisiko numerisk' },
  { name: 'POL_LINE_EXCESS_DESC',    type: 'text',                         description: 'Selvrisikobeløb i kroner' },
  { name: 'BROKER_PHONE',            type: 'text',                         description: 'Tlf. nr til agent' },
  { name: 'MAIN_PHONE',              type: 'text',    default: '98 98 98 98',           description: 'Hovednummer' },
  { name: 'DFHF_PHONE',              type: 'text',    default: '73 40 41 49',           description: 'DFHF telefonnummer' },
  { name: 'BROKER_EMAIL_CLAIM_AUTO', type: 'text',                         description: 'Agent mail' },
  { name: 'MAIN_EMAIL_CLAIM_AUTO',   type: 'text',    default: 'autoskade@forsia.dk',   description: 'Hoved mail' },
  { name: 'DFHF_EMAIL_CLAIM_AUTO',   type: 'text',    default: 'autoskade@detfagligehusforsikring.dk', description: 'DFHF mail' },
  { name: 'HANDLER_FIRST_NAME',      type: 'text',                         description: 'Fornavn skadebehandler' },
  { name: 'BROKER_NAME',             type: 'text',                         description: 'Agentnavn' },
  { name: 'CLAIM_NO',                type: 'text',                         description: 'Skadenummer' },
  { name: 'HANDLER_ID',              type: 'text',                         description: 'Sagsbehandler initialer' },
];
